### ISSUE TITLE
i get errors

### ISSUE THREAD

**Issue by MadaraV2492** [saintly2k/katana#3]
hello when i want to restart mysql i get this error Failed to restart mysqld.service: Unit not found. only for edeuacation

**Comment by saintly2k** [comment]
https://serverfault.com/questions/626922/no-mysqld-or-mysql-server-after-mariadb-server-install

**Comment by MadaraV2492** [comment]
i dont get this qould you make this for me ??

CREATE DATABASE ZTE_db;
use ZTE_db;
CREATE TABLE `history` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `user_id` int(10) unsigned NOT NULL,
  `time_sent` int(10) unsigned NOT NULL,
  `duration` int(10) unsigned NOT NULL,
  `command` text NOT NULL,
  `max_bots` int(11) DEFAULT '-1',
  PRIMARY KEY (`id`),
  KEY `user_id` (`user_id`)
);
 
CREATE TABLE `users` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `username` varchar(32) NOT NULL,
  `password` varchar(32) NOT NULL,
  `duration_limit` int(10) unsigned DEFAULT NULL,
  `cooldown` int(10) unsigned NOT NULL,
  `wrc` int(10) unsigned DEFAULT NULL,
  `last_paid` int(10) unsigned NOT NULL,
  `max_bots` int(11) DEFAULT '-1',
  `admin` int(10) unsigned DEFAULT '0',
  `intvl` int(10) unsigned DEFAULT '30',
  `api_key` text,
  PRIMARY KEY (`id`),
  KEY `username` (`username`)
);
 
CREATE TABLE `whitelist` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `prefix` varchar(16) DEFAULT NULL,
  `netmask` tinyint(3) unsigned DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `prefix` (`prefix`)
);

INSERT INTO users VALUES (NULL, 'zte', 'zte123321', 0, 0, 0, 0, -1, 1, 30, '');
quit;

**Comment by saintly2k** [comment]
hi, sorry no, i have no idea how to set this up anymore. please ask somebody else since i have no linux machine at the moment.
